###################################
#        General settings         #
###################################

Config:
  # English, German, Deutsch
  language: German
  
  lobbyCountdownLenght: 15
  lobbyIdleCountdownLenght: 20
  # The maximum gamelength in MINUTES!
  maxGameLenght: 20
  gameOverSound:
    enabled: true
    sound: ENDERDRAGON_GROWL
  gameOverDelay: 15
  gameOverBroadcastAt:
  - 15
  - 10
  - 5
  - 4
  - 3
  - 2
  - 1
  
  countdownBroadcastAt:
  - 15
  - 10
  - 9
  - 8
  - 7
  - 6
  - 5
  - 4
  - 3
  - 2
  - 1
  
  add1LoseAtLeavingGame: true
  sendStatsOnLeave: false
  sendStatsOnGameend: true
  
  seekerWaitDuration: 20
  newSeekerWaitDuration: 3
  
  roleMessage:
    fadeIn: 2
    duration: 5
    fadeOut: 2
  
  joinme:
    # Image Character
    # Change this to change what
    # character the image is made of.
    ########
    # Acceptable:
    # - BLOCK
    # - DARK_SHADE
    # - MEDIUM_SHADE
    # - LIGHT_SHADE
    character: 'BLOCK'

    # URL
    # Where to get the picture from.
    ########
    # Variables:
    # %uuid%   - Joined player's UUID
    # %pname%  - Joined player's Username
    url: 'https://minepic.org/avatar/8/%uuid%'
  
    # Async
    ########
    # Setting to true makes the picture generate
    # on an async thread. This has less performance
    # impact, but may delay the picture message.
    async: true
    
  prices:
    joinmePass: 1000
    seekerPass: 1000
    
  lobbyitems:
    leaveItem:
      # slot begins at 0
      slot: 8
      material: SLIME_BALL
      # Name in messages config!
      # Lore in messages config!
      amount: 1
      damage: 0
    shopItem:
      # slot begins at 0
      slot: 4
      material: CHEST
      # Name in messages config!
      # Lore in messages config!
      amount: 1
      damage: 0
    passItem:
      # slot begins at 0
      slot: 0
      material: PAPER
      # Name in messages config!
      # Lore in messages config!
      amount: 1
      damage: 0
    startItem:
      # slot begins at 0
      slot: 2
      material: EMERALD
      # Name in messages config!
      # Lore in messages config!
      amount: 1
      damage: 0
    