###################################
#        General settings         #
###################################

Config:
  # English, German, Deutsch
  language: English
  
  lobbyCountdownLenght: 15
  lobbyIdleCountdownLenght: 20
  # The maximum gamelength in MINUTES!
  maxGameLenght: 20
  gameOverSound:
    enabled: true
    sound: ENTITY_ENDERDRAGON_GROWL
  gameOverDelay: 15
  gameOverBroadcastAt:
  - 15
  - 10
  - 5
  - 4
  - 3
  - 2
  - 1
  
  countdownBroadcastAt:
  - 15
  - 10
  - 9
  - 8
  - 7
  - 6
  - 5
  - 4
  - 3
  - 2
  - 1
  
  gamemode:
    # Available: 0, 1, 2, 3, survival, creative, adventure, spectator
    lobby: survival
    inGame: survival
    ending: creative
    spectator: creative
  
  add1LoseAtLeavingGame: true
  sendStatsOnLeave: false
  sendStatsOnGameend: true
  teleportToMainLobbySpawn: true
  # If set to true the players will get teleportet to the Mainlobbyspawn at leaving or game end
  # If set to false the players will get teleportet to their last position at leaving or game end
  
  seekerWaitDuration: 20
  seekerWaitBroadcastAt:
  - 20
  - 10
  - 5
  - 4
  - 3
  - 2
  - 1
  newSeekerWaitDuration: 3
  
  blockedCommands:
    useAsWhitelist: false
    # if set to false this commands will get blocked
    # if set to true this commands won't get blocked
    commands:
    - 'blockedCommand1'
    - 'blockedCommand2'
  blockedCommandsForSpectator:
    useAsWhitelist: false
    # if set to false this commands will get blocked
    # if set to true this commands won't get blocked
    commands:
    - 'blockedCommandForSpectator1'
    - 'blockedCommandForSpectator2'
    
  unlimitedSeekerPassesWithPermission: true
  
  roleMessage:
    fadeIn: 2
    duration: 5
    fadeOut: 2
  
  joinme:
    character: 'BLOCK'
     # Image Character
     # Change this to change what
     # character the image is made of.
     ########
     # Acceptable:
     # - BLOCK
     # - DARK_SHADE
     # - MEDIUM_SHADE
     # - LIGHT_SHADE

    url: 'https://minepic.org/avatar/8/%uuid%'
     # URL
     # Where to get the picture from.
     ########
     # Variables:
     # %uuid%   - Joined player's UUID
     # %pname%  - Joined player's Username
  
    async: true
     # Setting to true makes the picture generate
     # on an async thread. This has less performance
     # impact, but may delay the picture message.
    
  prices:
    joinmePass: 1000
    seekerPass: 1000
    
  coins:
    hiders:
      moneyPerMinuteOfSurviving: 100
      moneyIfSurvivedTillEnd: 1000
    seekers:
      moneyPerFoundPlayer: 200
      moneyIfWinGame: 500
    
  lobbyitems:
    leaveItem:
      slot: 8
       # slot begins at 0
      material: SLIME_BALL
      # Name in messages config!
      # Lore in messages config!
      amount: 1
      damage: 0
    shopItem:
      slot: 4
       # slot begins at 0
      material: CHEST
      # Name in messages config!
      # Lore in messages config!
      amount: 1
      damage: 0
    passItem:
      slot: 0
       # slot begins at 0
      material: PAPER
      # Name in messages config!
      # Lore in messages config!
      amount: 1
      damage: 0
    startItem:
      slot: 2
       # slot begins at 0
      material: EMERALD
      # Name in messages config!
      # Lore in messages config!
      amount: 1
      damage: 0
  ingameitems:
    seekerStickItem:
      slot: 1
       # slot begins at 0
      material: STICK
      # Name in messages config!
      # Lore in messages config!
      amount: 1
      damage: 0
    