###################################
#        General settings         #
###################################

Config:
  language: English
  # English, German, Deutsch
  
  gamemode:
    # Available: 0, 1, 2, 3, survival, creative, adventure, spectator
    lobby: survival
    inGame: survival
    ending: creative
    spectator: creative
  
  add1LoseAtLeavingGame: true
  sendStatsOnLeave: false
  sendStatsOnGameend: true
  teleportToMainLobbySpawn: true
   # If set to true the players will get teleportet to the Mainlobbyspawn at leaving or game end
   # If set to false the players will get teleportet to their last position at leaving or game end
  
  blockedCommands:
    useAsWhitelist: false
     # if set to false this commands will get blocked
     # if set to true this commands won't get blocked
    commands:
    - 'blockedCommand1'
    - 'blockedCommand2'
  blockedCommandsForSpectator:
    useAsWhitelist: false
     # if set to false this commands will get blocked
     # if set to true this commands won't get blocked
    commands:
    - 'blockedCommandForSpectator1'
    - 'blockedCommandForSpectator2'
  
  joinme:
    character: 'BLOCK'
     # Image Character
     # Change this to change what
     # character the image is made of.
     ########
     # Acceptable:
     # - BLOCK
     # - DARK_SHADE
     # - MEDIUM_SHADE
     # - LIGHT_SHADE

    url: 'https://minepic.org/avatar/8/%uuid%'
     # URL
     # Where to get the picture from.
     ########
     # Variables:
     # %uuid%   - Joined player's UUID
     # %pname%  - Joined player's Username
  
    async: true
     # Setting to true makes the picture generate
     # on an async thread. This has less performance
     # impact, but may delay the picture message.
    
  prices:
    joinmePass: 1000
