###################################
#        General settings         #
###################################

Config:
  language: English
  # English, German, Deutsch
  
  scoreboardUpdateTicks: 10
  title:
    scheduled:
      fadeIn: 20
      stay: 60
      fadeOut: 20
    other:
      fadeIn: 5
      stay: 10
      fadeOut: 5
    showAllMinutes: 2
    showAtTimes:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
    - 15
    - 20
    - 25
    - 30